name: relightable-nr
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=9.0=h13b8566_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py37_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.2=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - nb_conda=2.2.1=py37_0
  - nb_conda_kernels=2.2.2=py37_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.0=py37_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1c=h7b6447c_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.2.2=py37_0
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - ptyprocess=0.6.0=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pyrsistent=0.14.11=py37h7b6447c_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytorch=1.1.0=py3.7_cuda9.0.176_cudnn7.5.1_0
  - pyzmq=18.1.0=py37he6710b0_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py37_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.3.0=py37_cu9.0.176_1
  - tornado=6.0.3=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - astroid==2.3.3
    - astropy==3.2.2
    - chardet==3.0.4
    - cycler==0.10.0
    - gast==0.3.2
    - google-pasta==0.1.7
    - googledrivedownloader==0.4
    - gputil==1.4.0
    - grpcio==1.24.0
    - h5py==2.10.0
    - idna==2.8
    - imageio==2.5.0
    - isodate==0.6.0
    - isort==4.3.21
    - joblib==0.14.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.3
    - markdown==3.1.1
    - matplotlib==3.1.1
    - mccabe==0.6.1
    - networkx==2.3
    - numpy==1.17.2
    - opencv-contrib-python==4.1.1.26
    - pandas==0.25.1
    - plyfile==0.7.1
    - protobuf==3.9.1
    - pylint==2.4.4
    - pyparsing==2.4.2
    - pyshtools==4.5
    - pytorch-msssim==0.1.3
    - pytz==2019.3
    - pywavelets==1.0.3
    - rdflib==4.2.2
    - requests==2.22.0
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - tensorboard==1.14.0
    - tensorboardx==1.5
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - termcolor==1.1.0
    - tqdm==4.35.0
    - trimesh==3.2.39
    - untangle==1.1.1
    - urllib3==1.25.6
    - werkzeug==0.16.0
    - wrapt==1.11.2
    - xarray==0.13.0
prefix: /root/anaconda3/envs/relightable-nr
